Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -148,11 +148,75 @@ jobs:
         git commit -m "Add SecureTomcatJDBC-test.jar artifact"
         git push origin main
 
+  deploy-test:
+    runs-on: ubuntu-latest
+    needs: build-test
+  
+    environment:
+      name: Test
+      url: https://gdbtst.gilead.com  
+    permissions:
+      id-token: write
+      contents: write
+    
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      
+    - name: Copy AppSpec File for Dev
+      run: |
+        cp appspec-test.yml appspec.yml
+        ls -la  # Verify the file is copied
+    - name: Configure Git
+      run: |
+         git config --global user.name 'github-actions[bot]'
+         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+    - name: Pull Latest Changes
+      run: git pull origin main
+
+    - name: Commit and Push AppSpec File
+      run: |
+         echo "Listing files before git add..."
+         ls -la  # List files to confirm appspec.yml is present
+    
+         if [ -f appspec.yml ]; then
+            echo "# Updated on $(date)" >> appspec.yml  # Append a comment with the current date and time
+            git add appspec.yml
+            git commit -m "Update appspec.yml file for test" || echo "No changes to commit"
+            git push origin main
+         else
+            echo "Error: appspec.yml not found in the root directory."
+         exit 1 
+         fi
+         
+    - name: List files
+      run: ls -la
+      
+    - name: Configure AWS Credentials using OIDC
+      uses: aws-actions/configure-aws-credentials@v2
+      with:
+        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
+        aws-region: us-west-2
+
+    - name: Create Code Deploy
+      id: deploy-dev
+      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
+      with:
+        application: RIDA_TST
+        appspec-file: appspec.yml
+
+    - name: Print Commit Message
+      uses: peter-evans/commit-comment@v2
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        body: |
+          @${{ github.actor }} this was deployed as ${{ steps.deploy-dev.outputs.deploymentId }} to group `${{ steps.deploy-dev.outputs.deploymentGroupName }}`.
+
   build-prod:
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Explicitly set the permissions for GITHUB_TOKEN
-    needs: build-test
+    needs: deploy-test
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
