Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -108,16 +108,16 @@ jobs:
         token: ${{ secrets.GITHUB_TOKEN }}
         body: |
           @${{ github.actor }} this was deployed as ${{ steps.deploy-dev.outputs.deploymentId }} to group `${{ steps.deploy-dev.outputs.deploymentGroupName }}`.
-  deploy-tst:
+deploy-tst:
     runs-on: ubuntu-latest
-    needs: deploy-dev
+    needs: build
   
     environment:
-      name: Test
-      url: gdbtst.gilead.com  
+      name: Dev
+      url: gdbdev.gilead.com  
     permissions:
       id-token: write
-      contents: read
+      contents: write
     
     steps:
     - name: Checkout code
@@ -125,12 +125,26 @@ jobs:
 
     - name: Copy AppSpec File for Tst
       run: cp appspec-tst.yml appspec.yml
-      
-    - name: Create Deployment Package
-      run: zip -r deployment-package.zip . -x "*.git*"
 
-    - name: List files in Deployment Package
-      run: unzip -l deployment-package.zip
+    - name: Configure Git
+      run: |
+         git config --global user.name 'github-actions[bot]'
+         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+    - name: Pull Latest Changes
+      run: git pull origin main
+
+    - name: Commit and Push AppSpec File
+      run: |
+         echo "Listing files before git add..."
+         ls -la  # List files to confirm appspec.yml is present
+         if [ -f appspec.yml ]; then
+           git add appspec.yml
+           git diff-index --quiet HEAD || git commit -m "Update appspec.yml file for Dev"
+           git push origin main
+         else
+           echo "Error: appspec.yml not found in the root directory."
+           exit 1
+         fi
       
     - name: List files
       run: ls -la
@@ -139,13 +153,13 @@ jobs:
       uses: aws-actions/configure-aws-credentials@v2
       with:
         role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
-        aws-region: ap-south-1
-    
+        aws-region: us-west-2
+
     - name: Create Code Deploy
-      id: deploy-tst
-      uses: webfactory/create-aws-codedeploy-deployment@v0.4.0
+      id: deploy-dev
+      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
       with:
-        application: GithubActionsXCodedeploy
+        application: RIDA_TST
         appspec-file: appspec.yml
 
     - name: Print Commit Message
@@ -153,50 +167,6 @@ jobs:
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         body: |
-          @${{ github.actor }} this was deployed as ${{ steps.deploy-tst.outputs.deploymentId }} to group `${{ steps.deploy-tst.outputs.deploymentGroupName }}`.
-  deploy-prod:
-    runs-on: ubuntu-latest
-    needs: deploy-tst
+          @${{ github.actor }} this was deployed as ${{ steps.deploy-dev.outputs.deploymentId }} to group `${{ steps.deploy-dev.outputs.deploymentGroupName }}`.
+          
   
-    environment:
-      name: Prod
-      url: gdb.gilead.com   
-    permissions:
-      id-token: write
-      contents: read
-    
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Copy AppSpec File for Prod
-      run: cp appspec-prod.yml appspec.yml
-      
-    - name: Create Deployment Package
-      run: zip -r deployment-package.zip . -x "*.git*"
-
-    - name: List files in Deployment Package
-      run: unzip -l deployment-package.zip
-      
-    - name: List files
-      run: ls -la
-      
-    - name: Configure AWS Credentials using OIDC
-      uses: aws-actions/configure-aws-credentials@v2
-      with:
-        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
-        aws-region: ap-south-1
-    
-    - name: Create Code Deploy
-      id: deploy-prd
-      uses: webfactory/create-aws-codedeploy-deployment@v0.4.0
-      with:
-        application: GithubActionsXCodedeploy
-        appspec-file: appspec.yml
-
-    - name: Print Commit Message
-      uses: peter-evans/commit-comment@v2
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        body: |
-          @${{ github.actor }} this was deployed as ${{ steps.deploy-prd.outputs.deploymentId }} to group `${{ steps.deploy-prd.outputs.deploymentGroupName }}`.
