Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -67,23 +67,27 @@ jobs:
 
     - name: Copy AppSpec File for Dev
       run: cp appspec-dev.yml appspec.yml
-      
     - name: Configure Git
       run: |
-        git config --global user.name 'github-actions[bot]'
-        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-    - name: Commit AppSpec File
+         git config --global user.name 'github-actions[bot]'
+         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+
+    - name: Pull Latest Changes
+      run: git pull origin main
+
+    - name: Commit and Push AppSpec File
       run: |
          echo "Listing files before git add..."
          ls -la  # List files to confirm appspec.yml is present
          if [ -f appspec.yml ]; then
-            git add appspec.yml
-            git commit -m "Add appspec.yml file"
-            git push origin main
+           git add appspec.yml
+           git commit -m "Update appspec.yml file for Dev"
+           git push origin main
          else
-            echo "Error: appspec.yml not found in the root directory."
-            exit 1
+           echo "Error: appspec.yml not found in the root directory."
+           exit 1
          fi
+      
       
     - name: List files
       run: ls -la
