Update Test-CI.yaml

diff --git a/.github/workflows/Test-CI.yaml b/.github/workflows/Test-CI.yaml
--- a/.github/workflows/Test-CI.yaml
+++ b/.github/workflows/Test-CI.yaml
@@ -1,15 +1,12 @@
-name: Build & Deploy for Test env
+name: Dev-CI.yaml
 
 on:
-  push:
-    branches:
-      - main
   workflow_run:
     workflows: ['Dev-CI.yaml']
     types: [completed]
 
 jobs:
-  build-tst:
+  build-test:
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Explicitly set the permissions for GITHUB_TOKEN
@@ -24,13 +21,13 @@ jobs:
         distribution: 'temurin'
         
     - name: Build with Ant for Test
-      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-tst.jar -propertyfile build-test.properties jar
+      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-test.jar -propertyfile build-test.properties jar
 
     - name: Upload Artifact for Test
       uses: actions/upload-artifact@v4
       with:
-        name: securetomcatjdbc-tst-jar
-        path: dist/SecureTomcatJDBC-tst.jar
+        name: securetomcatjdbc-test-jar
+        path: dist/SecureTomcatJDBC-test.jar
 
     - name: Configure Git
       run: |
@@ -42,19 +39,19 @@ jobs:
 
     - name: Commit JAR for Test
       run: |
-        mkdir -p tstjar
-        mv dist/SecureTomcatJDBC-tst.jar tstjar/
-        git add tstjar/SecureTomcatJDBC-tst.jar
-        git commit -m "Add SecureTomcatJDBC-tst.jar artifact"
+        mkdir -p testjar
+        mv dist/SecureTomcatJDBC-test.jar testjar/
+        git add testjar/SecureTomcatJDBC-test.jar
+        git commit -m "Add SecureTomcatJDBC-test.jar artifact"
         git push origin main
 
-  push-appspec-tst-yml:
+  push-appspec-test-yml:
     runs-on: ubuntu-latest
-    needs: build-tst
+    needs: build-test
   
     environment:
       name: Test
-      url: https://gdbtst.gilead.com  
+      url: https://gdbtest.gilead.com  
     permissions:
       id-token: write
       contents: write
@@ -63,7 +60,7 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
       
-    - name: Copy AppSpec File for Test
+    - name: Copy AppSpec File for test
       run: |
         cp appspec-test.yml appspec.yml
         ls -la  # Verify the file is copied
@@ -96,7 +93,7 @@ jobs:
          if [ -f appspec.yml ]; then
             echo "# Updated on $(date)" >> appspec.yml  # Append a comment with the current date and time
             git add appspec.yml
-            git commit -m "Update appspec.yml file for Test" || echo "No changes to commit"
+            git commit -m "Update appspec.yml file for Dev" || echo "No changes to commit"
             git push origin main
          else
             echo "Error: appspec.yml not found in the root directory."
@@ -106,9 +103,9 @@ jobs:
     - name: List files
       run: ls -la
   
-  deploy-tst:
+  deploy-test:
     runs-on: ubuntu-latest
-    needs: push-appspec-tst-yml
+    needs: push-appspec-test-yml
     environment:
       name: Test
       url: https://gdbtst.gilead.com
@@ -124,32 +121,23 @@ jobs:
         role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
         aws-region: us-west-2
     - name: Create Code Deploy
-      id: deploy-tst
+      id: deploy-test
       uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
       with:
         application: RIDA_TST
-      env:
-        BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.ref_name || 'unknown-branch' }}
-        
     - name: Retry Deployment on Failure
       if: failure()
       run: |
-        for i in {1..3}; do
-          echo "Attempt $i: Retrying deployment..."
-          sleep 30  # Wait for 30 seconds before retrying
-          webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
-          with:
-            application: RIDA_TST
-          if [ $? -eq 0 ]; then
-            echo "Deployment succeeded on attempt $i"
-            break
-          fi
-        done
+        echo "Retrying deployment..."
+        sleep 30  # Wait for 30 seconds before retrying
+        webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
+        with:
+          application: RIDA_TST
     - name: Print Commit Message
       uses: peter-evans/commit-comment@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         body: >
           @${{ github.actor }} this was deployed as ${{
-          steps.deploy-tst.outputs.deploymentId }} to group `${{
-          steps.deploy-tst.outputs.deploymentGroupName }}`.
+          steps.deploy-dev.outputs.deploymentId }} to group `${{
+          steps.deploy-dev.outputs.deploymentGroupName }}`.
